### ISSUE TITLE
📔 Fix the README.md links!

### ISSUE THREAD

**Issue by CosasDePuma** [easy-tensorflow/easy-tensorflow#12]
It is not a serious flaw, but in the file [README.md](https://github.com/easy-tensorflow/easy-tensorflow#tensorflow-tutorials) you have certain errors with the links belonging to the table of contents.

`#0 Introduction:`
Actual link: https://github.com/easy-tensorflow/easy-tensorflow/tree/master/0_Install_TensorFlow
Fixed link:  https://github.com/easy-tensorflow/easy-tensorflow/tree/master/0_Setup_TensorFlow

`#2 Logistic Regresion:`
Actual link: https://github.com/easy-tensorflow/easy-tensorflow/tree/master/2_Logistic_Regression
Fixed link: https://github.com/easy-tensorflow/easy-tensorflow/tree/master/2_Linear_Classifier

**Comment by amobiny** [comment]
Thanks for mentioning. 
We kept changing the file names and paths recently and weren't careful enough about it. I'll fix them.
