### ISSUE TITLE
error with section 1.5

### ISSUE THREAD

**Issue by sheksushant** [easy-tensorflow/easy-tensorflow#6]
this wont open : https://github.com/easy-tensorflow/easy-tensorflow/blob/master/1_Basics/5_Load_MNIST_Data.ipynb

neither on the website http://www.easy-tensorflow.com/basics

**Comment by amobiny** [comment]
This tutorial is not published yet and will be out soon.
Thanks for your feedback.

**Comment by sheksushant** [comment]
okay cool.
